### PR TITLE
ImageView: add panning if the user holds down the space bar

### LINKED ISSUE #98: Pan canvas when holding SPACE
A handy shortcut many graphics app support.

### PR DESCRIPTION
**Pull request by dsizzle**
If you hold SPACE, drag to pan, then release the mouse button but keep holding SPACE, clicking again to pan doesn't always work.  Releasing SPACE and pressing it again works.  

I discovered that WonderBrush has exactly the same problem - not sure if it's a Haiku issue or my setup? 

Fixes #98

### CODE REVIEW

**Comment by humdingerb** [comment]
Must be your setup. Works perfectly here.
With WonderBrush I sometimes get a "hanging" space key, or so it appears. I release the space bar, but the cursor is still the panning hand, and the mouse still drags the canvas. Once more hiting the space bar solves this. I haven't seen that with ArtPaint yet while panning madly for a few minutes...

BTW, you may want to try to split the coding style stuff into its own commit in the future. Makes discerning actual code changes easier for the generations to come. I know that it's very tempting to make a tiny style fix while doing code changes. And always commiting every little thing and later squash stuff with "git -i rebase" can be a drag... :)

Anyway, looks good. Let's merge!

**Comment by dsizzle** [comment]
Yay, I was hoping it was just on my end!

Wrt style fixes, I agree, that’s why I did #298 separately- but I should do more that way.

**Comment by Brunobasta** [comment]
The middle mouse button is nice to have too for pan

**Comment by dsizzle** [comment]
That already existed, I didn’t remove that functionality when I added this.

**Comment by humdingerb** [comment]
Strangely, I never tried the middle button... It does indeed pan the image,but IMO it's a bit weird. You move the mouse to the right and the image moves to the left. Can this work just like the SPACE panning, or is this - to me strange - panning behaviour appreciated by anyone?

**Comment by Brunobasta** [comment]
The image should move to the right and the image should move to the right, too.
Wonderbrush, Blender, and Photoshop and Illustrator it using it this way.

**Pull request merged**
