### PR TITLE
ColorPalette: accept B_SIMPLE_DATA as well as B_MIME_DATA message

### PR DESCRIPTION
**Pull request by dsizzle**
added support for Pe too for #257

### CODE REVIEW

**Comment by humdingerb** [comment]
Cool, now works wth Pe and Koder, too!

Does dropping a hex-value have to be handled differently than dropping an actual colour (e.g. from Colors!)?
You can drop a colour directly onto any swatch of the palette, but a hex-value drop will always change the currently selected swatch.
Conversely, you can drop a colour only on a swatch, dropping anywhere in the window does nothing. It could change the current swatch in this case, as dropping a hex-value does already.

**Comment by dsizzle** [comment]
I can make them consistent, should be easy.

**Comment by dsizzle** [comment]
ok, the color d&d works on the entire window like the hex values.

**Comment by humdingerb** [comment]
Sorry, still doesn't work here. I d&d a colour from the Colors! app and only when dropping on the big or a small swatch, it changes colour. Dropping anywhere else doesn't work.

**Comment by dsizzle** [comment]
Ok, this is one instance where I feel reasonably confident in asking if you can please try pulling the code and rebuilding… 😄  I removed the code from the big swatch and put it on the window, so the big swatch doesn’t even handle the d&d at all with this change.

**Comment by humdingerb** [comment]
Damn. I apparently didn't fetch your last changes to the branch...
Sorry about that.
Would it be easily possible to also drop hex-values on a specific swatch to change its colour? That's the only diff left between d&d colours and hex-values.

**Comment by dsizzle** [comment]
Should be no problem. I need to update this anyway since I accidentally left some commented-out code in there

**Comment by dsizzle** [comment]
ok, I think it all works now.  It was more work than I expected and so please check if I broke anything...

**Comment by humdingerb** [comment]
On the first drop of a hex-value (#FFF) onto a swatch, the alpha was set to 0, so #ffffff00. But every following drop worked perfectly. Couldn't reproduce no matter what I tried...
All other d&d action works fine.
I think it's good. Let's merge!

**Pull request merged**
