### PR TITLE
Ellipse selection: fix alpha for background when adding bitmap selection

### LINKED ISSUE #393: Ellipse selections sometimes select 1 pixel edge on right/bottom of image
I saw this before but thought it was fixed in #382 - seems to be throwing off the bounding box calculation for flipping.

### PR DESCRIPTION
**Pull request by dsizzle**
Fixes #393 

This is even sillier than the one line change from #382...

### CODE REVIEW

**Comment by humdingerb** [comment]
I don't see how the alpha channel plays into it... but I trust you know what you're doing. :)

Unfortunately, while it appeared at first to have solved the offset-while flipping, it's still happening when playing around long enough. Upon further testing: It appears that it works for the first image you open after launch, but if you close it and open another (without quitting the app), the bug re-appears...(Found #395 while doing that, btw.].

**Comment by dsizzle** [comment]
these ellipse selections are gonna be the death of me.  it doesn't make sense at all that it would happen upon opening a second window???  

but thanks, I will investigate more!!

**Comment by humdingerb** [comment]
Simple solution, as ArtPaint is for artists, get rid of the ellipses and have them draw their perfect circles with the freehand tool. :D

Observation, you have probably made yourself already: The further the ellipse is from the center of the image, the further it gets displaced on the first flip.

**Comment by dsizzle** [comment]
> Simple solution, as ArtPaint is for artists, get rid of the ellipses and have them draw their perfect circles with the freehand tool. :D

hahaha, good idea!

> Observation, you have probably made yourself already: The further the ellipse is from the center of the image, the further it gets displaced on the first flip.

right, this makes sense if the symptom is that there’s an errant 1 pixel selection along the right/bottom edge because the axis of flip is the center of the selection. So if you draw an ellipse touching the left side of the canvas, it oughta flip almost all the way over to right edge because the axis would practically be the center of the canvas

**Comment by dsizzle** [comment]
I think I fixed it - I was able to reproduce it simply by drawing an ellipse in the center, and then one on the far left.  The bounding box for the selection was getting calculated incorrectly. I can't break it anymore.

**Comment by humdingerb** [comment]
You have to be very string now...

I still see the same phenomenon:
* Launch ArtPaint
* Open image 1
* Select an ellipse and flip -> works
* Close image 1 (without quitting ArtPaint)
* Open image 2
* Select an ellipse and flip -> selected area gets displaced

(I deleted the objects folder and checked out PR 394 afresh before building.)

**Comment by dsizzle** [comment]
interesting, I can reproduce this using the steps you posted.

**Comment by dsizzle** [comment]
ok, now I'm pretty positive this is actually fixed.

**Comment by humdingerb** [comment]
Confirmed fixed!
Amazing how one stupid little pixel can wreak havoc...

**Pull request merged**
