### PR TITLE
AirBrushTool: attempting to get a smoother, better performing Airbrush

### PR DESCRIPTION
**Pull request by dsizzle**
- only calculate 1/4 of the brush and draw 4 pixels at once
- use LINEAR_INTERPOLATION in the CoordinateReader to get a smoother line
- adjusted linear interpolation to only get 1/10th of the coordinates
- remove snooze

@humdingerb can you give this a try to see if it's a better Airbrush experience?  It works a lot better on my end but I'm also not seeing what you're seeing, so this is just a more general attempt to improve the Airbrush feeling.

### CODE REVIEW

**Comment by humdingerb** [comment]
Nice. With this change it's again as fast as before!

**Comment by dsizzle** [comment]
Ok, I cleaned up the change a bit - please re-test and if it still behaves well I can merge it.

**Comment by humdingerb** [comment]
Still perfect. Good change!

**Comment by dsizzle** [comment]
merged!

**Pull request merged**
