### PR TITLE
FlipManipulator: make horiz and vertical flip respect selections

### PR DESCRIPTION
**Pull request by dsizzle**
This is part of #155.

### CODE REVIEW

**Comment by dsizzle** [comment]
this has exposed something else wrong with ellipses...sometimes the flip axis is NOT the center of the selection but something...else.  Only saw the issue with ellipses.

**Comment by humdingerb** [comment]
Indeed, the first flip of an ellipse selection moves it to the right (h-flip) or down (v-flip).
Separate issue, oryou wanna try fixing that in this PR?

**Comment by dsizzle** [comment]
It’s separate. I filed #393 for it

**Comment by humdingerb** [comment]
And we merge...

**Pull request merged**
