### PR TITLE
Migrated from custom translation to Locale kit

### LINKED ISSUE #58: Localize using catkeys
Currently ArtPaint has its own localization scheme (English, French and German), but the text really needs updating in places.  It would be best to swtich to the Haiku catkeys scheme in the process.

### PR DESCRIPTION
**Pull request by dsizzle**
This is a pretty large commit - removed all of the custom localization code and replaced with Locale Kit.  Generated all the catkeys for Dutch, English, Finnish, French, German, and Spanish.

Fixes #58

### CODE REVIEW

**Comment by humdingerb** [comment]
Wow, that was a lot of work! :)
Do you plan on localizing all add-ons too?

@korli: Any idea why the build fails on the haiku-ci machine?

**Comment by korli** [comment]
@dsizzle  please rebase on master. Thanks.

**Comment by dsizzle** [comment]
@korli it's already rebased?  the ci error is some kind of timeout.

**Comment by humdingerb** [comment]
Alright. I suppose it makes most sense to put the catkeys on Polyglot once the addons are localized as well.

**Comment by korli** [comment]
> @korli it's already rebased? the ci error is some kind of permission error

This branch is 20 commits ahead, 1 commit behind HaikuArchives/ArtPaint:master.

**Comment by dsizzle** [comment]
That's very strange. I checked earlier and it said my branch was up to date... but just now I see that it's 1 commit behind. 🤔

**Comment by dsizzle** [comment]
ok, now it should really be rebased, and it passed the ci check.

**Comment by humdingerb** [comment]
Alright, let's merge! Thanks!

**Pull request merged**
