### PR TITLE
Selection: draw bitmap to view before drawing polygons

### LINKED ISSUE #367: Freehand selections don't work properly with certain others
Steps to reproduce:

1. Use the magic wand and click on an empty canvas to select the entire thing
2. Draw a selection with the freehand tool while holding OPT

The selection subtracts the entire bounding-box of the freehand selection, not the selection itself:
0bad

Expected result:\
0good

It works fine if you subtract from a rectangle selection or select-all, but for magic wand and elliptical selections, trying to use a freehand selection on top behaves badly.

It also is problematic for additive selections:
0bad2

But again, it's ONLY on top of magic wand or elliptical selections; rectangles work fine with freehand on top, both additive and subtractive: 
0good2

### PR DESCRIPTION
**Pull request by dsizzle**
Fixes #367

### CODE REVIEW

**Comment by humdingerb** [comment]
Besides there being conflicts to be solved...

Very weird: I checked out this PR and it did seem to solve the issues descriibed in #367. I quit ArtPaint and restarted to do more testing, and now I'm not able to make any selection. I removed all objects and re-buildm still no selections.
Does it work on your end?

**Comment by humdingerb** [comment]
To add: It does work if you first use Ellipse or Magic wand as selection tools.
"Select all" doesn't work, "Select non-transparent" does.

**Comment by dsizzle** [comment]
Sorry about the conflicts, probably because I did too many PRs at once. 

I’ll check it out. Seems like my change has unintended consequences?

**Comment by humdingerb** [comment]
Conflicts are no problem. Until it's time to merge. :)

**Comment by dsizzle** [comment]
abandoning this branch as it seems like it's badly out of sync

**Pull request closed without merging**
