### PR TITLE
Eraser Tool: added "Pressure" slider to control opacity of erasure

### LINKED ISSUE #176: Replace Transparency tool with options for Eraser
The Transparency tool is hard to understand.  The Eraser tool would be more intuitive with some options:

- "Pressure" or "Strength" or something to say how transparent to erase
- "Hardness" like the Brush tool for soft edge erasing

### PR DESCRIPTION
**Pull request by dsizzle**
Blur tool was giving me fits so I took a break to do this.

Fixes #176 
 
(this was the last piece to close out that ticket)

### CODE REVIEW

**Comment by humdingerb** [comment]
I know that the "use current" checkbox is kinda linked to the "Size" slider, but it'd look neater to have the sliders together and have the checkbox below them. That the checkbox only influences the Size not the Pressure setting, should be clear by only the Size slider being en/disabled when clicking the checkbox.

**Comment by dsizzle** [comment]
Yeah I was wondering about that but went for the logical grouping. Happy to make this change if it looks better.

**Comment by dsizzle** [comment]
fixed!

**Comment by humdingerb** [comment]
Very good!

**Pull request merged**
