### PR TITLE
ColorPalette: disambiguate "Colors" for translation

### LINKED ISSUE #579: "Colors" string improvement
In `ColorPalette.cpp`, there are two instances of the string `Colors`. Since they are the same, Pootle only shows one translation, however, the menu string needs to be different from the title one (at least for Turkish).

The menu item should also not use string concatenation, which looks like the source of the error in the first place.

### PR DESCRIPTION
**Pull request by humdingerb**
Fixes #579.

### CODE REVIEW

**Comment by dsizzle** [comment]
This change looks good to me. Ship it!

**Comment by humdingerb** [comment]
Thought you might want to test your new merging powers... 😃

**Comment by dsizzle** [comment]
I considered it but didn’t really have time to deal with it if anything went wrong… 😄

**Comment by humdingerb** [comment]
Alright. Your time will come. :)

**Pull request merged**
