### PR TITLE
WindowGUIManipulator: restore MessageReceived virtual function

### PR DESCRIPTION
**Pull request by dsizzle**
need to re-add this function after #613

### CODE REVIEW

**Comment by dsizzle** [comment]
merged without review; needed to fix missing runtime symbol

**Comment by humdingerb** [comment]
Sorry about that. I thought if the MessageReceived() just calls the parent class' (is that what you call it?), MessageReceived() function, it could just as well be removed...

**Comment by dsizzle** [comment]
parent or base.  I can take the blame for this; I remember making a comment along the lines of being able to delete these types of functions.  Without going into detail, in this case it's the inheritance chain - the derived classes (like the AddOns) need that virtual function.

**Comment by humdingerb** [comment]
Ah, sort of an inheritence tax we have to pay for the greedy add-on heirs...

**Pull request merged**
