### PR TITLE
Selector tool: add Ellipse option

### LINKED ISSUE #118: Selection tool: add circle/ellipse shape
As the tool icon suggests, even. :)

### PR DESCRIPTION
**Pull request by dsizzle**
Fixes #118

### CODE REVIEW

**Comment by humdingerb** [comment]
Nice. (I agree with your implied suggestion to not generate updated en.catkeys with every little change, but when a few string changes have piled up or an impending release.)

One thing, or rather 4 small ones, there are little appendices at the 0, 3, 6 and 9 o'clock positions:

circle

**Comment by dsizzle** [comment]
That’s an unfortunate artifact of the ellipse drawing code, unrelated to this PR. I had to replace that code when I did all that alpha drawing stuff. It’s better than before but not perfect as you can see. We will need new ellipse code at some point to support the rotation and stroke thickness.

**Comment by humdingerb** [comment]
You mean to improve BView's StrokeEllipse or ArtPaint specific code?
You plan to do that at a later time and this PR is ready to merge?

**Comment by humdingerb** [comment]
Very good. Merging. 

Despite those automatic builds keep failing...:

```
artpaint/paintwindow/PaintWindow.cpp:61:40: warning: null character(s) ignored
   61 | #include <private/interface/WindowInfo.h>
      |                                        ^
artpaint/paintwindow/PaintWindow.cpp:61: error: missing terminating > character
   61 | #include <private/interface/WindowInfo.h>
      | 
artpaint/paintwindow/PaintWindow.cpp:61:10: fatal error: private/interface/WindowInfo. label);: No such file or directory
   61 | #include <private/interface/WindowInfo.h>
      |          ^
compilation terminated.
/boot/system/develop/etc/makefile-engine:300: recipe for target 'objects_artpaint/PaintWindow.o' failed
make: *** [objects_artpaint/PaintWindow.o] Error 1
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

**Pull request merged**
