### PR TITLE
Fixed a few coding style issues

### PR DESCRIPTION
**Pull request by harshit-sharma-gits**
Fixed the coding style in multiple files as per the Guidelines, mostly the function descriptions.

### CODE REVIEW

**Comment by korli** [comment]
Which guidelines are you referring to?

**Comment by humdingerb** [comment]
Looks good, but please change the commit message to "Fix a few coding style issues". haiku-format finds a lot more transgressions...

**Comment by harshit-sharma-gits** [comment]
I have changed the commit message as suggested.
Please add the GSoC2022 label to this pull request, Thanks!

**Comment by korli** [comment]
Last time coding style patches weren't of interest for GSoC. Or has it changed?

**Comment by harshit-sharma-gits** [comment]
It is mentioned in the GSoC Contributors FAQ, that the code contribution could be "code style cleanup"

Capture

**Comment by korli** [comment]
OK, but this would better help if the coding style cleanup is related to your project proposal.

**Comment by humdingerb** [comment]
Merging anyway. More PRs are always possible... :)

**Comment by dsizzle** [comment]
Yeah I panicked a little when I saw this as I am touching a lot of the files for converting to Locale kit.  Thankfully this doesn't seem to have added any merge conflicts. :laughing:

**Comment by humdingerb** [comment]
@dsizzle , yeah this kind of simple style changes that are normally auto-merged without issues.

**Pull request merged**
