### PR TITLE
Selection: add option to select all non-transparent pixels

### PR DESCRIPTION
**Pull request by dsizzle**
Added option to select all non-transparent pixels in the current layer.  I called it "All pixels" in the menu but open to suggestions!

### CODE REVIEW

**Comment by humdingerb** [comment]
That is supposed to select all pixels that are fully, 100% non-transparent, right?
Since pixels could have an alpha of <255 and are still visible as pixels, "All non-transparent" or "All opaque" would be better.

There's a strange effect when using the Airbrush tool with a half transparent colour and selecting "All pixels":

**Comment by dsizzle** [comment]
Actually I am trying to preserve the alpha and select any pixel that is not *fully* transparent. The idea is that if you have something with an antialised edge it’d be nice to select those pixels if you transform the selection instead of leaving behind some dots.

For some reason GitHub isn’t showing me your screenshot but I will experiment with some transparent stuff when I have a chance.  I didn’t try an airbrush stroke, but it works great on Ducky and Walter. :D

**Comment by humdingerb** [comment]
> Actually I am trying to preserve the alpha and select any pixel that is not fully transparent. The idea is that if you have something with an antialised edge it’d be nice to select those pixels if you transform the selection instead of leaving behind some dots.

Right, that makesmore sense. Although, since that only works when the object with the antialiased edge is on an otherwise transparent layer, you could just as well just "Select all"...
I suppose it'll really become usefull when ArtPaint gets something like "Stroke/Fill selection".
"All non-transparent" seems to be an OK label. Or "All visible"? - that may be misunderstood though, e.g. all in the currently visible main-window-clipping of the canvas.

> For some reason GitHub isn’t showing me your screenshot

Nor me... this was the shot:
Airbrush

> but it works great on Ducky and Walter. :D

Well... it does look a bit frayed (this is pasting the "All pixel"ed Walter as a new layer on top of some image), or is that related to #286 :

all-pixels-pasted

**Comment by dsizzle** [comment]
That airbrush selection screenshot is terrible, and is related to #309 …

I don’t think the Walter edges are the same issue as #286 - looks like the antialiasing didn’t all get selected?  Hmm.

**Comment by dsizzle** [comment]
It might actually be the same issue as #286?  

Also - this is exposing other issues...I used the "erase" tool and the "select non-transparent" is selecting the part I erased! 
0ghost

**Comment by humdingerb** [comment]
Spooky! Trick or treat, ArtPaint?!

**Comment by dsizzle** [comment]
so actually fixing #286 *did* fix this too.  Works way better on Walter and paintbrush strokes.  Also airbrush strokes.

Although it does expose the issue that apparently the brushes and eraser are painting almost-but-not-quite transparent pixels?

**Comment by humdingerb** [comment]
Nice! Merge now?

> Although it does expose the issue that apparently the brushes and eraser are painting almost-but-not-quite transparent pixels?

Looks like it, "Clear" canvas/layer also create non-transparent pixels. The colour picker shows an alpha of 1 instead of 0.

**Comment by dsizzle** [comment]
Yes, I think it works well enough to merge if you haven’t found any other concerns

**Comment by humdingerb** [comment]
It's good. Merge!

**Pull request merged**
