### PR TITLE
Fix drawing artifacts

### LINKED ISSUE #2: When adjustable width lines are drawn, they often leave grey lines behind.
**Creator: **
**URL: http://dev.osdrawer.net/issues/585**

Found by Gabriel Boorse as part of Google Code In 2012.

_CAUTION: comments not extracted from issues. See OsDrawer or the WaybackMachine for issue comments._

### PR DESCRIPTION
**Pull request by dsizzle**
Fixed by redrawing the affected portion of the screen. Performance shows no difference drawing a 1600x1200 rectangle in a VM on a 5 year old laptop, so I suspect it's plenty fast enough this way, and solves the drawing issues with no Haiku change. 

Fixes #2, #3, #4, and #32

### CODE REVIEW

**Comment by humdingerb** [comment]
Works nicely! Keeping the PR open over the weekend to see if others see any issues with this solution.

**Comment by humdingerb** [comment]
One thing I just noticed: When you use the rectangle tool and keep moving the mouse in and out to make the rect bigger/smaller, you'll see the pixels of the image wobble slightly. A bit like heat haze...
These tiny changes will remain after you lift the mouse button and the rectangle is drawn in its final position. Same for the ellipse tool, of course.

Important: it seems to have something to do with the zoom level. Try to first zoom to 100%, the zoom in to 200%.

**Comment by dsizzle** [comment]
That may be hard to avoid. Unless your image is exactly powers of two in dimensions, there could be floating point rounding at any zoom level other than 100%...but I will take a look.

**Comment by Begasus** [comment]
Build failure on 32bit nightly:
```
g++ -c artpaint/paintwindow/PaintWindow.cpp  -Iartpaint/  -Iartpaint/Utilities/  -Iartpaint/application/  -Iartpaint/controls/  -Iartpaint/layers/  -Iartpaint/paintwindow/  -Iartpaint/tools/  -Iartpaint/viewmanipulators/  -Iartpaint/windows/  -Iobjects_artpaint/ -I-   -O3    -o "objects_artpaint/PaintWindow.o"
g++ -c artpaint/paintwindow/PaintWindowMenuItem.cpp  -Iartpaint/  -Iartpaint/Utilities/  -Iartpaint/application/  -Iartpaint/controls/  -Iartpaint/layers/  -Iartpaint/paintwindow/  -Iartpaint/tools/  -Iartpaint/viewmanipulators/  -Iartpaint/windows/  -Iobjects_artpaint/ -I-   -O3    -o "objects_artpaint/PaintWindowMenuItem.o"
g++ -c artpaint/paintwindow/StatusView.cpp  -Iartpaint/  -Iartpaint/Utilities/  -Iartpaint/application/  -Iartpaint/controls/  -Iartpaint/layers/  -Iartpaint/paintwindow/  -Iartpaint/tools/  -Iartpaint/viewmanipulators/  -Iartpaint/windows/  -Iobjects_artpaint/ -I-   -O3    -o "objects_artpaint/StatusView.o"
/Opslag/ArtPaint/artpaint/paintwindow/StatusView.cpp: In method `StatusView::StatusView()':
/Opslag/ArtPaint/artpaint/paintwindow/StatusView.cpp:96: call of overloaded `SetVisibleItem(int)' is ambiguous
/boot/system/develop/headers/os/interface/CardLayout.h:19: candidates are: void BCardLayout::SetVisibleItem(long int)
/boot/system/develop/headers/os/interface/CardLayout.h:20:                 void BCardLayout::SetVisibleItem(BLayoutItem *)
/Opslag/ArtPaint/artpaint/paintwindow/StatusView.cpp: In method `status_t StatusView::DisplayToolsAndColors()':
/Opslag/ArtPaint/artpaint/paintwindow/StatusView.cpp:137: call of overloaded `SetVisibleItem(int)' is ambiguous
/boot/system/develop/headers/os/interface/CardLayout.h:19: candidates are: void BCardLayout::SetVisibleItem(long int)
/boot/system/develop/headers/os/interface/CardLayout.h:20:                 void BCardLayout::SetVisibleItem(BLayoutItem *)
/boot/system/develop/etc/makefile-engine:300: recipe for target 'objects_artpaint/StatusView.o' failed
make: *** [objects_artpaint/StatusView.o] Error 1
```

**Comment by dsizzle** [comment]
@Begasus interesting - that issue is unrelated to this commit.  Seems like an issue with BCardLayout on 32-bit? 

I wonder if casting the value would solve it.

**Comment by Begasus** [comment]
@dsizzle I cloned your fork for the build, don't know if there are other changes, anyway, maybe this would be better in another issue (updated comment above)

**Comment by humdingerb** [comment]
> These tiny changes will remain after you lift the mouse button and the rectangle is drawn in its final position.

After playing a bit more: these tiny changes go away again if you change magnification. So they not actually permanantly change the image. Which is good. :)

**Comment by Begasus** [comment]
Confirmed OK, (thanks for the build fix @dsizzle ) :)

**Comment by dsizzle** [comment]
I think if we push this and #141 we ought to do a release.  Even just the fixed black canvas #81 made ArtPaint usable again, but now it's even a little better.  What do you think?

**Comment by humdingerb** [comment]
Agreed. I'll create a new release and up the middle version, so v2.1.2 -> v2.2.0 . I'd say your great work on updating and fixing code warrents that easily. :)

**Comment by dsizzle** [comment]
Thanks for making the release, and the kind words!  

btw, #2 #3 #4 can also be closed with this fix.  Maybe #32 ?

**Comment by humdingerb** [comment]
Closed the remaining issues manually. Nomally the "Fixes '#'" should close those automatically. I guess it doesn't take when doing several comma-separated...

**Comment by PeteCA** [comment]
On Wed, Apr 20, 2022 at 09:28:06PM -0700, Dale Cieslak wrote:
> Fixed by redrawing the affected portion of the screen. Performance shows no difference drawing a 1600x1200 rectangle in a VM on a 5 year old laptop, so I suspect it&#39;s plenty fast enough this way, and solves the drawing issues with no Haiku change. 
> 
> Fixes #2, #3, #4, and #32

 Wow!  That's the big one!  Well done!

**Pull request merged**
