### PR TITLE
StraightLineTool: add pressure setting for opacity control

### PR DESCRIPTION
**Pull request by dsizzle**
...and one more with a Pressure option.  Not sure what else will need pressure...maybe Hairy Brush?

### CODE REVIEW

**Comment by humdingerb** [comment]
Same suggestions as in #512 : 
> I know that the "use current" checkbox is kinda linked to the "Size" slider, but it'd look neater to have the sliders together and have the checkbox below them. That the checkbox only influences the Size not the Pressure setting, should be clear by only the Size slider being en/disabled when clicking the checkbox.

**Comment by humdingerb** [comment]
> Not sure what else will need pressure...maybe Hairy Brush?

Yes. Most would probably link their tablet-pressure to the Size slider, but it's nice to have options.

**Comment by dsizzle** [comment]
fixed

**Comment by humdingerb** [comment]
Works well. I was wondering for a second, if the "Enable antialiasing" should also be available when using the "current brush". At least if it's a 100% hardness brush you end up with blocky edges.
But then I thought, if users wanted smoothness, they can adjust the hardness of the brush...
And so we merge.

**Pull request merged**
