### PR TITLE
Selection: add option to hide selection borders.

### LINKED ISSUE #284: Selection menu: Add "Hide border" item
It's be nice to be able to hide the selection border "ants".
I suppose it would be a checkmarkable item "Hide border".
To acknowledge peoples' Photoshop muscle-memory, I propose to have the shortcut ALT+H.

### PR DESCRIPTION
**Pull request by dsizzle**
Fixes #284

### CODE REVIEW

**Comment by humdingerb** [comment]
Changing menu items' labels isn't so nice.  It's better to use a checkmarked menu item and keep the label constant. It's even in the under-maintained HIG...
One advantage is that you always see at a glance if the bottom menu item has a checkmark or not, without having to read any text.

**Comment by humdingerb** [comment]
Also, what do you think about adding a separator above the "Hide borders"?
There are quite a few items in the Selection menu already, so it's nice to have something the eye can skip to. Also, it would separate the items changing the selection in any way and "non-destructive" actions.

**Comment by dsizzle** [comment]
Excellent point about the checkmark instead of the label - fixed that! 

Also added the separator.

**Comment by humdingerb** [comment]
Perfect.

**Pull request merged**
