### PR TITLE
Manipulators: when pressing enter, execute settings in window

### PR DESCRIPTION
**Pull request by dsizzle**
- on enter, read values of controls

Addresses #282 

I only did the main operations, no add-ons

### CODE REVIEW

**Comment by humdingerb** [comment]
Oh, I thought I could manipulate with the mouse and hit enter to apply when reading the commit message... :)

Anyway, there's something strange going on:
* Open an image.
* ALT+R to rotate.
* Rotate with mouse, say ca. -45°.
* Click into manipulator window and hit ENTER or click OK.

--> The mouse-set angle should be used, the manipulator window just be dismissed. Instead the image is rotated further.

**Comment by dsizzle** [comment]
Is it just rotate?

**Comment by humdingerb** [comment]
Yep, seems just to occur when rotating.

**Comment by dsizzle** [comment]
Cool, thank you for testing. I thought my overall idea was sound, but after I saw your comment I remembered that I’d seen similar behavior when I did something else with rotate- snapping, perhaps?

**Comment by dsizzle** [comment]
Ok, rotate seems to be fixed.

**Comment by humdingerb** [comment]
Yep, works now, thanks!

**Pull request merged**
