### PR TITLE
Int32 bcardlayout

### LINKED ISSUE #138: x86 build: StatusView - SetVisibleItem(int) issue
Haiku R1B3 x86 - Ref: https://github.com/HaikuArchives/ArtPaint/commit/b86463b388110ed1d240388432733c6ac69e5851

'SetVisibleItem(int)' is ambigous - conflicts with OS Header file  with os/interface/CardLayout.h (i.e. SetVisibleItem(long int))

### PR DESCRIPTION
**Pull request by dsizzle**
BCardLayout.SetVisibleItem needs a cast of the parameter to build on 32-bit Haiku

Fixes #138

### CODE REVIEW

**Comment by humdingerb** [comment]
Pays off to try a build on 32bit Haiku once in a while. ;)

**Comment by Begasus** [comment]
> Pays off to try a build on 32bit Haiku once in a while. ;)

It does ;) :+1:

**Comment by dsizzle** [comment]
@Begasus is there anything special I need to do to build on 32-bit?  I get this error:

```
Assembler messages:
FATAL: can't create objects_artpaint/HSPolygon.o: Bad data
```

**Comment by Begasus** [comment]
> @Begasus is there anything special I need to do to build on 32-bit? I get this error:
> 
> ```
> mkdepend: Bad data
> mkdepend: Can't write 'objects_artpaint/HSPolygon.d'
> g++ -c ...etc...
> Assembler messages:
> FATAL: can't create objects_artpaint/HSPolygon.o: Bad data
> ```

normaly not, worked just fine here

**Comment by humdingerb** [comment]
Maybe you need to remove all object dirs first. Addons too.
`rm -r addons/AddOns/*/obj*`

**Comment by dsizzle** [comment]
IDK, I made a fresh VM, installed 32-bit Haiku, cloned the repo, and it builds fine. :shrug:

**Pull request merged**
