### PR TITLE
ImageView: draw ellipse indicating rough size of brush

### PR DESCRIPTION
**Pull request by dsizzle**
This is a first version for #128 -  I think it works pretty well.  My concern was performance since it's drawing on every single mouse movement, but it seems to be fine. 

Works for Freeline,  Airbrush, Eraser, Blur, and Transparency.  I didn't do Hairy brush because the "size" of it is dependent on how quickly you move the brush. 

Eventually I want to try using the new selection algorithm to see if I can draw the actual shape of a brush rather than just an ellipse.

### CODE REVIEW

**Comment by dsizzle** [comment]
can't decide if this should have the option to turn off.  Maybe.  But it's so dang useful to actually know what you're going to paint...

**Comment by humdingerb** [comment]
Very cool!

A few observations:
* It's a bit flickery and the outline disappears if you stop the mouse-movement, but keep the mouse-button pressed. Try moving very slowly, pixel-by-pixel to see the outline dis/re-appearing.
* Using a largish brush, on first click - without moving the mouse - you see one-pixel lines at the top, bottom, left, right of the outline ellipse.
* The straight line tool could show such a preview-outline if it's not in "Adjustable width" mode.
* If there should be a setting for this, the Misc tab of the settings still has room for a checkbox. I agree, though, it's very useful and can't come up with a situation you wouldn't want the brush-outline...

**Comment by dsizzle** [comment]
I think the flickering and your second bullet are because it’s drawing when the mouse button is not pressed, and when the button is pressed the actual painting takes over which may fight with it. 

Not sure how I feel about the straight line one. Might make the most sense if “use current brush” is selected though.

in terms of the setting I was thinking like the cursor mode, there could be a third option for “show tool size”?

**Comment by humdingerb** [comment]
> I think the flickering and your second bullet are because it’s drawing when the mouse button is not pressed, and when the button is pressed the actual painting takes over which may fight with it.

But once you are actually drawing, there's no need for the brush size outline. Maybe only draw it when there's no mouse-down?

> there could be a third option for “show tool size”?
Yep. The two existing radio buttons plus the new checkbox "Show tool size".

**Comment by dsizzle** [comment]
ok, now it doesn't draw if there's a mouse button pressed.  

I tried adding this to StraightLine Tool and it felt a little weird. 

haven't done the option yet.

**Comment by dsizzle** [comment]
...and now there's a setting in the Misc section of the app settings.

**Comment by dsizzle** [comment]
Ok, I went for the grand prize and now it draws the actual shape of the brush!!!

**Comment by humdingerb** [comment]
> Ok, I went for the grand prize and now it draws the actual shape of the brush!!!

Fantastic!
I guess using polygons is a throw forward to supporting arbitrarily shaped brushes. An angled rectangular brush appears a bit scraggy. Ellipses are fine. I suppose it's not trivial to optimize rectangular brush sizes to use a regular 4 point rectangle? It's no biggie though.

One thing: The brush size outline doesn't reappear after mouse-up, but only once you've moved the mouse.I think it should.

**Comment by humdingerb** [comment]
Alright, I'm convinced. Ready to merge.

> How often is the mouse still?

Only after a very long day at  the rat race... :)

**Comment by dsizzle** [comment]
Speaking of rat races I thought about this whole driving to the office, and I wonder if your comment actually nailed it:

> The brush size outline doesn't reappear after mouse-up

maybe if I add code to draw in MouseUp it would feel more correct?

**Comment by humdingerb** [comment]
> maybe if I add code to draw in MouseUp it would feel more correct?

I'd say so. There are situations where you don't move the mouse, like you have the Blur or Transparency tool with a largish brush and park the mouse over a part of the image and just click the mouse button a few times until you're satisfied with the look. In that case you wouldn't see the brush size after the first click. Not a big issue, but if the brush size could easily be drawn at MouseUp as well, that'd be nice.

**Pull request merged**
