### PR TITLE
Use BNumberFormat for percentage values

### PR DESCRIPTION
**Pull request by bitigchi**
Also refactor the zoom sub-menu generation logic.

### CODE REVIEW

**Comment by dsizzle** [comment]
Thanks for this change!  

Unfortunately the help text at the bottom of the window incorrectly displays the help text: 

percent

Also a minor nitpick, but the "1600%" now has the locale-based thousands separator so it shows as "1,600%" which feels odd for a zoom %.

**Comment by bitigchi** [comment]
Ah, it used to work okay, but apparently broken in the final revision. Will fix the broken render.

For the 1,600; it just uses the system settings for thousands separator. I'm not sure if it's possible to disable it just yet, I'll look into it.

**Comment by bitigchi** [comment]
It looks like disabling the thousands separator is not currently exposed in Haiku's ICU implementation (feel free to correct me). Previously 1600 was not included, I included it because the bottom slider went all the way up to 1600. Shall I remove it?

**Comment by humdingerb** [comment]
Just for my education, what's the problem this solves?

**Comment by bitigchi** [comment]
> Just for my education, what's the problem this solves?

It formats the percentages according to the locale settings. For instance:

- %100 for Turkish and some other Turkic languages
- 100 % for French and some Scandinavian folks
- 100 ٪ for Arabic etc.

Detailed info here: https://en.wikipedia.org/wiki/Percent_sign

**Comment by bitigchi** [comment]
Well, that's the whole point of this PR, otherwise I'd just mark them translatable and be done with it.

I'd rather go ahead with this PR and make it rather an incentive to people to see it and complete the implementation in Haiku. Otherwise it may go unnoticed for a very long time.

I see this kind of zoom value in other applications anyway, but if you think that's an issue, fair enough.

**Comment by humdingerb** [comment]
> Otherwise it may go unnoticed for a very long time.

I doubt many people study the ArtPaint source. A ticket at Trac should be more effective.

**Comment by bitigchi** [comment]
It looks like I've already opened a ticket in the past, but have forgotten about it.

They don't need to see the source, they could see the menu entry or the slider value and try to fix it if they get confused by it.

**Comment by dsizzle** [comment]
I think this change is a good change and makes the code cleaner. The comma separator doesn’t bother me that much, I just thought it might be an option to the formatter.

**Comment by humdingerb** [comment]
If the 1,000 separator offends, we could add this at the appropriate places:

```
	if (magLevel >= 10.0) {
		BString seperator(fNumberFormat.GetSeparator(B_GROUPING_SEPARATOR));
		fPercentData.RemoveFirst(seperator);
	}
```

**Comment by bitigchi** [comment]
Neat! I'll try this and report back.

**Comment by humdingerb** [comment]
It might be worth to cache the seperator string in a member variable. At least when using the zoom slider, the percentage calculation can be triggered rapidly. (Or is that only done once when releasing the mouse?)

**Comment by bitigchi** [comment]
I couldn't get it to work on both places with the appropriate changes. It would be great if someone could try it at a convenient time...

**Comment by humdingerb** [comment]
I committed the changes via "Edit" of the GitHub website, because I'm not sure how to push stuff into this PR...
We'll squash those additional changes into one commit.
Only waiting for @dsizzle's blessing. :)  (Feel free to squash&commit)

**Comment by bitigchi** [comment]
For the sub menu, my change was identical, probably I forgot to clear the cache... LGTM!

**Comment by dsizzle** [comment]
Looks good to me!

**Comment by dsizzle** [comment]
squashed and merged.

**Comment by bitigchi** [comment]
Hooray!

**Comment by humdingerb** [comment]
Teamwork! 😃
@dsizzle : next time you squash,  you could edit the commit message to remove ugly or redundant stuff.

**Pull request merged**
