### PR TITLE
UX tweaks: reverse mouse-wheel zoom, remove ALT from zoom, etc.

### LINKED ISSUE #337: Zoom with mouse-wheel (without ALT), don't scroll canvas
As mentioned at https://github.com/HaikuArchives/ArtPaint/issues/317#issuecomment-1285217367:

> We now have a much nicer way to scroll around the canvas - SPACEBAR panning.
Advantages:
>
> Arbitrary panning direction (versus: only vertically or - with additional CTRL - horizontally at a time)
Arbitrary panning speed (versus: max. 2 speeds (with additional SHIFT))
Allows mouse wheel zooming without holding ALT, thus freeing it for some other action.

### LINKED ISSUE #338: Middle-mouse-button panning: reverse or remove
Middle-mouse-button panning currently works the opposite way as SPACEBAR panning. Left is right. Up is down... Madness.
I think we should have it either work the same as SPACEBAR panning, or remove it for a possibly better usage of the middle-mouse-button in the future.

### LINKED ISSUE #339: Reverse mouse-wheel zoom direction
All other graphics apps I checked on Haiku zoom in on mouse wheel forward.

### PR DESCRIPTION
**Pull request by dsizzle**
also:
- restored ALT for color picker
- reversed middle-mouse-button panning to match SPACE panning

Fixes #337 
Fixes #338 
Fixes #339

### CODE REVIEW

**Comment by humdingerb** [comment]
> restored ALT for color picker

Now you went too far! :)
This will launch the instant color picker when you want to create a centered rectangle/ellipse (selection).

**Comment by dsizzle** [comment]
oh right.  for some reason I thought the zoom was the reason we changed that. oops

**Comment by dsizzle** [comment]
ok, undid that silly change!

**Comment by humdingerb** [comment]
Perfect!

**Pull request merged**
