### PR TITLE
ImageView: Press ESC to cancel manipulators.

### PR DESCRIPTION
**Pull request by dsizzle**
Part of #282

### CODE REVIEW

**Comment by humdingerb** [comment]
Very nice! I'm a major user of "ESC = Dismiss". \o/
Q: Would it be equally easy to have "RETURN = trigger active button (default being OK)" for those manipulator windows? Once you use the mouse, the manipulator window loses focus and the RETURN doesn't reach it.

Merging in any case.

**Comment by dsizzle** [comment]
I don't think it would be equally easy but might not be too hard.  lemme add that to #282

**Comment by dsizzle** [comment]
oh also I really wish ESC worked for intelligent scissors too...

**Comment by humdingerb** [comment]
:+1

**Pull request merged**
