### PR TITLE
Anti-Dither: Use a BSpinner

### LINKED ISSUE #94: AntiDither addon: Use a BSpinner control
...instead of the BTextControl:

anti-dither

### PR DESCRIPTION
**Pull request by humdingerb**
Set minimal block size to "1". A block size of "0" makes no sense...
Fixes #94

### CODE REVIEW

**Comment by korli** [comment]
Looks good to me.

**Comment by dsizzle** [comment]
Looks fine, just seems like an overly large field. 

Also apparently BSpinner is an undocumented control?

**Comment by humdingerb** [comment]
> Looks fine, just seems like an overly large field.

That just appears like that , because that size includes the label and +/- widgets. I deemed it necessary, because without setting the size, it would fill the width of the window. But, after a second thought, and I didn't like setting the max size explicitely in the first place, I now went to put the BSpinner in a horizontal group and add some Glue(). There, better. :)

> Also apparently BSpinner is an undocumented control?

Yes, it's in a private header that I had to add int he addon's makefile.

**Comment by humdingerb** [comment]
@korli , those new github-action seems to fail... builds OK locally.

**Comment by korli** [comment]
it looks like your branch isn't rebased.

**Comment by korli** [comment]
no, now  pkgman says it wants a reboot. this is annoying.

**Pull request merged**
