### PR TITLE
FillTool: make gradient range track mouse (aka intuitive)

### PR DESCRIPTION
**Pull request by dsizzle**
- also added Radial gradient option

Alpha still doesn't work, but aside from alpha I think this is much better.  I also added Radial gradients.

...as an aside, I tried to make the "linear" and "radial" buttons as well as the "preview" checkbox disable when you turn off gradient fill, but for some reason it totally breaks the functionality?  

Anyway please try out the gradient drawing and lmk if it is more intuitive.

the related issue is #182

### CODE REVIEW

**Comment by humdingerb** [comment]
It works much better than before!
However, it still applies the colours the wrong way round, I think:
* You have a gradient going from black to white
* You click in the canvas and move the mouse to the right
* The result is a gradient from white to black

**Comment by dsizzle** [comment]
well, I flipped the colors.  Still no luck on alpha.

**Comment by dsizzle** [comment]
baby steps. Alpha works, but only if you don't use Preview mode.

**Comment by humdingerb** [comment]
Cool! You'll get there. :)
You say when to merge the status quo. It's already much nicer than before.

**Comment by dsizzle** [comment]
Ok, I think it all works now - please give it a try!  If it works fine for you then please merge.

**Comment by humdingerb** [comment]
Those were quite huge baby steps... :)
Appears to work perfectly! \o/

**Pull request merged**
