### PR TITLE
Release 2.3

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by bitigchi** [comment]
Is Github glitching or I can't see the Catalan, Portuguese, and Turkish catkeys?

**Comment by humdingerb** [comment]
The PR consists of 2 commits.

**Comment by bitigchi** [comment]
Yes, and both commits do not seem to contain these language files.

**Comment by humdingerb** [comment]
Oh, you're right. Forgot to add, will do later.

**Comment by korli** [comment]
> Oh, you're right. Forgot to add, will do later.

And the build fails because of this it seems.

**Comment by humdingerb** [comment]
All fixed now. Thanks for keeping an eye out everyone.

**Comment by dsizzle** [comment]
For the release notes, one item tha you might add is the Color Reducer add-on crash fix for GLA mode.  Otherwise they look good.

**Comment by humdingerb** [comment]
Alright. Added. Let's merge, release and update the haikuports recipe.
Congrats on the release! :)

**Pull request merged**
